image: maven:3-jdk-8

stages:
  - build

  variables:
  MAVEN_CLI_OPTS: "--batch-mode --show-version"

build:
  stage: build
  script: mvn $MAVEN_CLI_OPTS package install
  artifacts:
    paths:
      - target/display4j-core-2.0-SNAPSHOT.jar